'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { motion } from 'framer-motion'
import {
  LifeBuoy, MessageSquare, CheckCircle, ChevronDown, ChevronUp,
  Phone, Mail, Clock, Loader2
} from 'lucide-react'
import toast from 'react-hot-toast'
import Navbar from '@/components/Navbar'
import { TICKET_CATEGORY_LABELS, type TicketCategory } from '@/lib/support-tickets'

const FAQ_ITEMS = [
  {
    q: 'How does the food donation process work?',
    a: 'Submit a food donation via the Donate Food page. Our AI analyzes the food details, matches it with the nearest NGO, and arranges a pickup — either by an NGO volunteer or a platform volunteer.',
  },
  {
    q: 'What qualifies as safe food to donate?',
    a: 'Food must be freshly cooked or properly packaged, not previously served, and free from contamination. Expired, open, or improperly stored food cannot be accepted.',
  },
  {
    q: 'How do I become a volunteer?',
    a: 'Register with the "Volunteer" role. Once verified, you\'ll see available pickups in the Volunteer Hub. Accept a pickup, collect from the donor, and deliver to the matched NGO.',
  },
  {
    q: 'My donation is stuck on "Pending" — what should I do?',
    a: 'Our system automatically matches donations to NGOs every few minutes. If it\'s been over 30 minutes, contact support using the form below and we\'ll investigate.',
  },
  {
    q: 'How is the NGO matched to my donation?',
    a: 'Our AI considers distance (within 10 km), NGO capacity, dietary preferences, and current volunteer availability to find the best match.',
  },
  {
    q: 'Can I cancel a donation I\'ve submitted?',
    a: 'Yes, contact our support team immediately with your donation ID. If no volunteer has been assigned yet, we can cancel it.',
  },
  {
    q: 'How do I get a Food Safety Certificate?',
    a: 'Certificates are auto-generated by our AI system after every successful delivery. Volunteers receive them in their dashboard after marking a delivery as complete.',
  },
  {
    q: 'Is my personal data shared with NGOs or volunteers?',
    a: 'Only your name and general pickup area are shared. Phone numbers and full addresses are not disclosed to other users.',
  },
]

const CATEGORIES = Object.entries(TICKET_CATEGORY_LABELS) as [TicketCategory, string][]

export default function SupportPage() {
  const router = useRouter()

  // Form state
  const [name,        setName]        = useState('')
  const [email,       setEmail]       = useState('')
  const [phone,       setPhone]       = useState('')
  const [category,    setCategory]    = useState<TicketCategory | ''>('')
  const [subject,     setSubject]     = useState('')
  const [description, setDescription] = useState('')
  const [submitting,  setSubmitting]  = useState(false)
  const [ticketId,    setTicketId]    = useState<string | null>(null)

  // FAQ accordion
  const [openFaq, setOpenFaq] = useState<number | null>(null)

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!category)                     { toast.error('Select a category'); return }
    if (description.trim().length < 20){ toast.error('Please describe your issue (min 20 chars)'); return }

    setSubmitting(true)
    try {
      const res = await fetch('/api/support', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify({ name, email, phone, category, subject, description }),
      })
      const data = await res.json()
      if (!data.success) throw new Error(data.error)
      setTicketId(data.data.id)
      toast.success('Ticket submitted! We\'ll respond within 24 hours.')
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Failed to submit ticket')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="min-h-screen bg-mesh">
      <Navbar />
      <main className="max-w-5xl mx-auto px-4 pt-28 pb-20">

        {/* Hero */}
        <motion.div
          initial={{ opacity: 0, y: 18 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-14"
        >
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-amber-100 border border-amber-300 text-amber-800 text-xs font-semibold mb-5">
            <LifeBuoy className="w-3.5 h-3.5" />
            Support Center
          </div>
          <h1 className="text-3xl font-bold text-slate-900 mb-3">How can we help you?</h1>
          <p className="text-slate-600 max-w-xl mx-auto text-sm leading-relaxed">
            Browse the FAQ or submit a ticket. Our team monitors support requests 7 days a week and responds within 24 hours.
          </p>
        </motion.div>

        {/* Quick contact chips */}
        <div className="grid grid-cols-3 gap-4 mb-14">
          {[
            { icon: Phone, label: 'Call Us', sub: '+91 98765 43210', color: 'text-emerald-700 bg-emerald-50 border-emerald-200' },
            { icon: Mail,  label: 'Email Us', sub: 'help@geminigrain.in', color: 'text-blue-700 bg-blue-50 border-blue-200' },
            { icon: Clock, label: 'Response Time', sub: 'Within 24 hours', color: 'text-amber-700 bg-amber-50 border-amber-200' },
          ].map(({ icon: Icon, label, sub, color }) => (
            <div key={label} className={`flex items-center gap-3 px-4 py-3.5 rounded-2xl border ${color}`}>
              <Icon className="w-5 h-5 shrink-0" />
              <div>
                <div className="text-xs font-semibold">{label}</div>
                <div className="text-xs opacity-80 mt-0.5">{sub}</div>
              </div>
            </div>
          ))}
        </div>

        <div className="grid lg:grid-cols-2 gap-10">

          {/* FAQ */}
          <div>
            <div className="flex items-center gap-2 mb-6">
              <MessageSquare className="w-5 h-5 text-slate-700" />
              <h2 className="text-lg font-bold text-slate-900">Frequently Asked Questions</h2>
            </div>
            <div className="space-y-2">
              {FAQ_ITEMS.map((item, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 6 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.04 }}
                  className="rounded-xl border border-slate-200 bg-white overflow-hidden"
                >
                  <button
                    onClick={() => setOpenFaq(openFaq === i ? null : i)}
                    className="w-full flex items-center justify-between px-4 py-3.5 text-left hover:bg-slate-50 transition-colors"
                  >
                    <span className="text-sm font-medium text-slate-900 pr-4">{item.q}</span>
                    {openFaq === i
                      ? <ChevronUp className="w-4 h-4 text-slate-500 shrink-0" />
                      : <ChevronDown className="w-4 h-4 text-slate-500 shrink-0" />
                    }
                  </button>
                  {openFaq === i && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      className="px-4 pb-4"
                    >
                      <p className="text-sm text-slate-600 leading-relaxed">{item.a}</p>
                    </motion.div>
                  )}
                </motion.div>
              ))}
            </div>
          </div>

          {/* Contact Form */}
          <div>
            <div className="flex items-center gap-2 mb-6">
              <LifeBuoy className="w-5 h-5 text-slate-700" />
              <h2 className="text-lg font-bold text-slate-900">
                {ticketId ? 'Ticket Submitted' : 'Submit a Ticket'}
              </h2>
            </div>

            {ticketId ? (
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                className="bg-white rounded-2xl border border-emerald-200 p-8 text-center"
              >
                <div className="w-16 h-16 rounded-full bg-emerald-100 flex items-center justify-center mx-auto mb-4">
                  <CheckCircle className="w-8 h-8 text-emerald-600" />
                </div>
                <h3 className="text-base font-bold text-slate-900 mb-1">Your ticket is open</h3>
                <p className="text-sm text-slate-600 mb-3">
                  Ticket ID: <span className="font-mono bg-slate-100 px-2 py-0.5 rounded text-slate-800">{ticketId}</span>
                </p>
                <p className="text-sm text-slate-600 mb-6">
                  We&apos;ll email you at <strong>{email}</strong> with an update within 24 hours.
                </p>
                <button
                  onClick={() => {
                    setTicketId(null)
                    setName(''); setEmail(''); setPhone(''); setCategory(''); setSubject(''); setDescription('')
                  }}
                  className="px-5 py-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-white text-sm font-semibold transition-colors"
                >
                  Submit Another
                </button>
              </motion.div>
            ) : (
              <form onSubmit={handleSubmit} className="bg-white rounded-2xl border border-slate-200 p-6 space-y-4">
                {/* Name + Email */}
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1.5">
                      Full Name <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="text"
                      value={name}
                      onChange={(e) => setName(e.target.value)}
                      required
                      placeholder="Your name"
                      className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 bg-slate-50 text-sm text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-amber-300 focus:border-transparent transition-all"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1.5">
                      Email <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="email"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      required
                      placeholder="you@email.com"
                      className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 bg-slate-50 text-sm text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-amber-300 focus:border-transparent transition-all"
                    />
                  </div>
                </div>

                {/* Phone */}
                <div>
                  <label className="block text-xs font-semibold text-slate-700 mb-1.5">Phone (optional)</label>
                  <input
                    type="tel"
                    value={phone}
                    onChange={(e) => setPhone(e.target.value)}
                    placeholder="+91 98765 43210"
                    className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 bg-slate-50 text-sm text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-amber-300 focus:border-transparent transition-all"
                  />
                </div>

                {/* Category */}
                <div>
                  <label className="block text-xs font-semibold text-slate-700 mb-1.5">
                    Category <span className="text-red-500">*</span>
                  </label>
                  <div className="grid grid-cols-2 gap-2">
                    {CATEGORIES.map(([key, label]) => (
                      <button
                        key={key}
                        type="button"
                        onClick={() => setCategory(key)}
                        className={`text-left px-3 py-2.5 rounded-xl border text-xs font-medium transition-all ${
                          category === key
                            ? 'border-amber-400 bg-amber-50 text-amber-900'
                            : 'border-slate-200 bg-slate-50 text-slate-700 hover:border-slate-300 hover:bg-white'
                        }`}
                      >
                        {label}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Subject */}
                <div>
                  <label className="block text-xs font-semibold text-slate-700 mb-1.5">
                    Subject <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    value={subject}
                    onChange={(e) => setSubject(e.target.value)}
                    required
                    placeholder="Brief summary of your issue"
                    maxLength={120}
                    className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 bg-slate-50 text-sm text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-amber-300 focus:border-transparent transition-all"
                  />
                </div>

                {/* Description */}
                <div>
                  <label className="block text-xs font-semibold text-slate-700 mb-1.5">
                    Description <span className="text-red-500">*</span>
                  </label>
                  <textarea
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    required
                    placeholder="Describe your issue in detail. Include any relevant IDs, steps to reproduce, or what you expected to happen…"
                    rows={5}
                    maxLength={1000}
                    className="w-full px-3.5 py-3 rounded-xl border border-slate-200 bg-slate-50 text-sm text-slate-900 placeholder:text-slate-400 resize-none focus:outline-none focus:ring-2 focus:ring-amber-300 focus:border-transparent transition-all"
                  />
                  <div className="flex justify-between mt-1">
                    <span className="text-xs text-slate-400">Min 20 characters</span>
                    <span className="text-xs text-slate-400">{description.length}/1000</span>
                  </div>
                </div>

                <button
                  type="submit"
                  disabled={submitting || !name || !email || !category || !subject || description.trim().length < 20}
                  className="w-full flex items-center justify-center gap-2 py-3 rounded-xl bg-slate-900 hover:bg-slate-800 disabled:opacity-50 disabled:cursor-not-allowed text-white font-semibold text-sm transition-colors"
                >
                  {submitting ? (
                    <><Loader2 className="w-4 h-4 animate-spin" />Submitting…</>
                  ) : (
                    'Submit Ticket'
                  )}
                </button>
              </form>
            )}
          </div>

        </div>
      </main>
    </div>
  )
}
